# Run the build.
FROM golang:1.17 as builder
WORKDIR "/api"

COPY pkg pkg
COPY cmd cmd
COPY go.* .

RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -o api ./cmd/api 

# Build the actual container.
FROM alpine:latest
WORKDIR "/api"

COPY --from=builder "/api" .

RUN apk add bash

COPY scripts scripts

CMD ["./scripts/run.sh"]