FROM alpine:latest

RUN echo <<EOF >> ./index.http
HTTP/1.1 200 OK
Content-Type: text/html; charset=UTF-8
Server: netcat!

<!doctype html>
<html><body><h1>A webpage served by netcat</h1></body></html>
EOF

RUN echo <<EOF >> ./serve.sh \
while true; do cat index.http | nc -l 80; done
EOF

RUN chmod +x ./serve.sh

CMD ["./serve.sh"]