# Run the build.
FROM golang:1.17 as builder
WORKDIR "/cli"

COPY . .

RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -o cli ./cmd/cli 

# Build the actual container.
FROM alpine:latest
WORKDIR "/cli"

COPY --from=builder "/cli" .

CMD ["sh", "-c", "./cli --email ${ML_EMAIL} --password ${ML_PASSWORD} --course ${ML_COURSE}"]