services:
  - type: web
    name: mlcal-api
    env: docker
    dockerfilePath: "Dockerfile.api"
    repo: https://github.com/elauffenburger/mlcal
    plan: free
    branch: main
    numInstances: 1
    healthCheckPath: /calendar?text
    pullRequestPreviewsEnabled: true
    envVars:
      - fromGroup: mlcal-api
      - key: REDIS_HOST
        fromService:
          name: mlcal-api-redis
          type: redis
          property: host
      - key: REDIS_PORT
        fromService:
          name: mlcal-api-redis
          type: redis
          property: port
      - key: PORT
        value: 80
  - type: redis
    name: mlcal-api-redis
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
    plan: free