services:
  - type: web
    name: mlcal-api
    env: docker
    dockerfilePath: "Dockerfile.api"
    repo: https://github.com/elauffenburger/mlcal
    plan: free
    branch: main
    numInstances: 1
    healthCheckPath: /calendar?text
    envVars:
      - fromGroup: mlcal-api
      - key: REDIS_HOST
        fromRedis:
          name: mlcal-api-redis
          property: host
      - key: REDIS_PORT
        fromRedis:
          name: mlcal-api-redis
          property: port
      - key: PORT
        value: 80
redises:
  - name: mlcal-api-redis
    plan: ephemeral